#!/usr/bin/env python
import sqlite3
import argparse
import sys


def initiate_parser():
    parser = argparse.ArgumentParser(description="Dump google chrome history")
    parser.add_argument("db", 
                        action="store",
                        type=str,
                        help="Chrome history file usually ~/.config/google-chrome/Default/History")
    parser.add_argument("urls", 
                        action="store", 
                        type=str, 
                        help="The file to store history dump")
    return parser


def main():
    parser = initiate_parser()
    args = parser.parse_args()
    f = open(args.urls, 'wb')
    try:
        conn = sqlite3.connect(args.db)
        c = conn.cursor()
        f.write('url,visit_count\n')
        for row in c.execute('SELECT url,visit_count from urls'):
            f.write('%s,%s\n' % (row[0], row[1]))
        f.close()
    except:
        print "Cannot open file using sqlite3" , sys.exc_info()


if __name__ == "__main__":
    main()
